-- INSERT INTO artist (name) VALUES
-- ('Oliver Xu'),
-- ('Brennan Bowen'),
-- ('Jerry Yan');
-- SELECT * FROM artist ORDER BY name DESC LIMIT 10;
-- SELECT * FROM artist ORDER BY NAME ASC LIMIT 5;
-- SELECT * FROM artist WHERE name LIKE 'Black%';
-- SELECT * FROM artist WHERE name LIKE '%Black%';
